version: "3.8"
services:
  api: &python
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${DOCKER_EXPOSE_PORT:-8000}:8000"
    volumes:
      - ./src/:/usr/src/app/src
    depends_on:
      db:
        condition: service_healthy
    command: python -m uvicorn src.api.app:app --env-file .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      handler-service:

  db:
    restart: unless-stopped
    image: postgres:15.1
    env_file: .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
    networks:
      handler-service:

networks:
  handler-service:
